#!/usr/bin/env bash

__func_defered=()
defer() {
    __func_defered+=("$*")
}
do_defer() {
    for ((i=${#__func_defered[@]}-1;i>=0;i--)); do
        if ! eval "${__func_defered[i]}"; then
            echo "eval cmd failed, cmd: \"${__func_defered[i]}\"" >&2
        fi
    done
}
trap do_defer EXIT

