#!/usr/bin/env bash
set -ex


# opt_volumes=(
#     "/dev/loop0"
#     "/dev/loop1"
#     "/dev/loop2"
#     "/dev/loop3"
#     "/dev/loop4"
# )
# opt_cvolume="/dev/loop5"
# opt_vg="raid6_group"
# opt_lv="raid6_vol"

opt_volumes=()
opt_cvolume=
opt_vg="raid6_group"
opt_lv="raid6_vol"

pvcreate "${opt_volumes[@]}"
vgcreate "${opt_vg}" "${opt_volumes[@]}"
lvcreate --type raid6 --extents 100%FREE --name "${opt_lv}" "${opt_vg}"

if [ -n "${opt_cvolume}" ]; then
    pvcreate "${opt_cvolume}"
    vgextend "${opt_vg}" "${opt_cvolume}"
    lvcreate --type cache-pool --extents 100%FREE --name cache_pool "${opt_vg}" "${opt_cvolume}"
    lvconvert --type cache --cachepool "${opt_vg}/cache_pool" "${opt_vg}/${opt_lv}"
fi

