#!/usr/bin/env bash
set -ex

opt_volumes=(
)

# create raid
mdadm \
    --create /dev/md0 \
    --level=6 \
    --raid-devices="${#opt_volumes[@]}" \
    "${opt_volumes[@]}"

# save mdadm config
mdadm --detail --scan | tee -a /etc/mdadm/mdadm.conf
update-initramfs -u

# remove raid
mdadm --stop /dev/md0
mdadm --zero-superblock "${opt_volumes[@]}"
