#!/usr/bin/env bash
set -ex

info() {
    echo "[info]" "$@"
}

err() {
    echo "[error]" "$@" 2>&1
}

die() {
    local code="$1"
    shift

    err "$@"
    exit "${code}"
}

__func_defered=()
do_defer() {
    for ((i=${#__func_defered[@]}-1;i>=0;i--)); do
        if ! eval "${__func_defered[i]}"; then
            die 1 "eval cmd failed, cmd: \"${__func_defered[i]}\""
        fi
    done
}
trap do_defer EXIT
defer() {
    __func_defered+=("$*")
}

# opt_volumes=(
#     "/dev/loop0"
#     "/dev/loop1"
#     "/dev/loop2"
#     "/dev/loop3"
#     "/dev/loop4"
# )
opt_volumes=()

do_raid6() {
    local md="$1"
    shift
    if [ -z "${md}" ]; then
        die 1 "undefined md"
    fi
    mdadam --create "${md}" --level=6 --raid-devices="${#opt_volumes[@]}" "${opt_volumes[@]}"
}

main() {
    local action=
    while (($#)); do
        case "$1" in
            --volume)
                opt_volumes+=("$2")
                shift 2
                ;;
            --raid6)
                action="do_raid6"
                shift
                ;;
            *)
                break
                ;;
        esac
    done

    if [ -z "${action}" ]; then
        die 1 "undefined action"
    fi
    "${action}" "$@"
}

main "$@"
