#!/usr/bin/env bash
set -e

info() {
    echo "[info] " "$@"
}

__func_defered=()
defer() {
    __func_defered+=("$*")
}
do_defer() {
    for ((i=${#__func_defered[@]}-1;i>=0;i--)); do
        if ! eval "${__func_defered[i]}"; then
            echo "eval cmd failed, cmd: \"${__func_defered[i]}\"" >&2
        fi
    done
}
trap do_defer EXIT

opt_output=output.mp4

opt_headers=()
opt_concurrent=16
opt_keep=

do_download() {
    local temp="$(mktemp -d)"
    if [[ ${opt_keep} == y ]]; then
        info "keep workdir ${temp}"
    else
        defer "rm -rf ${temp}"
    fi

    local url="$1"
    local url_prefix="$(dirname ${url})"
    local m3u8="$(basename ${url})"

    local cmd=("curl"
        "-o" "${temp}/${m3u8}"
        "-A" "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
    )
    for header in "${opt_headers[@]}"; do
        cmd+=("-H" "${header}")
    done
    cmd+=("${url}")
    "${cmd[@]}"
    cat "${temp}/${m3u8}" \
        | while read -r line; do
            if [[ "${line}" != \#* ]]; then
                printf "${url_prefix}/%s\n" "${line}"
            else
                printf "${url_prefix}/%s\n" "${line}"
            fi
        done \
        >"${temp}"/frags.lst
    cmd=("aria2c"
        "-d" "${temp}"
        "-i" "${temp}/frags.lst"
        "-U" "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
        "-m" "8"
        "-j" "${opt_concurrent}"
        "-c" "true"
        "--http-accept-gzip" "true"
    )
    for header in "${opt_headers[@]}"; do
        cmd+=("--header=${header}")
    done
    "${cmd[@]}"
    mkdir -p "$(dirname "${opt_output}")"
    ffmpeg -hide_banner -y -i "${temp}/${m3u8}" -c copy "${opt_output}"
}

main() {
    while (($#)); do
        case $1 in
            -header | --header)
                opt_headers+=("$2")
                shift 2
                ;;
            -k | --keep)
                opt_keep=y
                shift
                ;;
            -j | --max-concurrent-downloads)
                opt_concurrent="$2"
                shift 2
                ;;
            -o | --output)
                opt_output="$2"
                shift 2
                ;;
            *)
                break
                ;;
        esac
    done
    do_download "$@"
}

main "$@"

