#!/usr/bin/env python3

import sys
import argparse

import cv2


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('-o', '--output', default='result.jpg',
                        help='Resulting image. The default is `result.jpg`.')
    parser.add_argument('imgs', nargs='+', help='input images')
    return parser.parse_args()


def main():
    options = parse_args()

    imgs = [cv2.imread(x) for x in options.imgs]
    stitcher = cv2.Stitcher.create()
    status, pano = stitcher.stitch(imgs)

    if status != cv2.Stitcher_OK:
        print("Can't stitch images, error code = %d" % status)
        sys.exit(-1)

    cv2.imwrite(options.output, pano)


if __name__ == '__main__':
    main()
